apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  labels:
    app: test
spec:
  ports:
  - name: http-default
    port: 80
    targetPort: 9898
  selector:
    fronted-by: podinfo-service
  type: ClusterIP