apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: podinfo
  namespace: app-podinfo
  labels:
    app: podinfo
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service podinfo-service"]'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - image: docker.io/stefanprodan/podinfo
        name: podinfo
        ports:
          - containerPort: 9898
